	; Strings to accompany werner3.zap

	.GSTR STR?117,""
	.GSTR STR?127,"               The End.

Are you going to make another pitiful attempt?"
	.GSTR STR?379,"   10  Inserting spoon in slot"
	.GSTR STR?388,"   10  Pull the lever"
	.GSTR STR?383,"   10  Taking the basketball"
	.GSTR STR?384,"   10  Taking the danish pastry"
	.GSTR STR?382,"   10  Taking the Duran Duran album"
	.GSTR STR?381,"   10  Taking the paper bag"
	.GSTR STR?385,"   10  Taking the salami sausage"
	.GSTR STR?386,"   10  Taking the yellow 3 skilling banco stamp"
	.GSTR STR?380,"   10  Taking the ZX Spectrum"
	.GSTR STR?387,"   10  Waking the old man"
	.GSTR STR?389,"  100   TOTAL POINTS"
	.GSTR STR?152," are"
	.GSTR STR?172," doesn't"
	.GSTR STR?171," don't"
	.GSTR STR?153," is"
	.GSTR STR?183," N = Next"
	.GSTR STR?179," RETURN = See hint"
	.GSTR STR?185," RETURN = See topics"
	.GSTR STR?149," Try rephrasing the command."
	.GSTR STR?132," turn"
	.GSTR STR?0,"

...as in a dream, you can see yourself being slapped on the back by a person with german accent, thence tumbling downa short escalator, and then, the image of the aforementioned man producing various items from a steaming briefcase,a 30 ft. deep well, and seven useless objects carried by an old and wise-looking, yet oddly inane man. The images are blurred, as if viewed through a veil of some sort (probably silk). These images give way for another set of images: of you doing your homework, jogging in the forest, washing the car, pruning the fruit trees, involved in activities including the opposite sex... in short everything you could have been doing if you weren't playing this game. The images fade away...


Werner's Quest, Revisited - 3. Rance the Dungeonkeeper
Original Quill game by Jan Åberg, 1985, 1986
Source extracted from C64-version with Unquill v0.11 and converted to ZIL by Henrik Åsman, 2019
Type 'ABOUT' for more details about this version."
	.GSTR STR?22,"""All ye who go around saying unto famous music personalities: Hello Taylor; verily, for thee it shouldst be easier to complete thy quest; thou shouldst be rewardeth with one of the items upon thine computer printout"""
	.GSTR STR?25,"""Hello Adventurer!

 To complete this quest, you must gather the following objects:

 A Danish Pastry
 A Paper Bag (brown, with peepholes)
 A Yellow 3 Skilling Banco Stamp
 A Duran Duran Album
 A Salami Sausage
 A Basketball
 A ZX Spectrum (oh, that lovely computer!(joke))

 When you are in possession of these, you must find the Werner Dungeon Adventure Player Inspector, who will show you to the Final Conquest.

 Bye for now,
 Rance the Dungeonkeeper"""
	.GSTR STR?136,"%25"
	.GSTR STR?124,"(worn over your head, which makes you feel silly)"
	.GSTR STR?134,"."
	.GSTR STR?125,"A complete and utter absence of belongings."
	.GSTR STR?113,"A wizard appears, carrying a broken zipper out of which fall various items, among them a pair of jeans, a poodle and a pair of speakers. These items immediately disappear through the magic of stage-craft. He is almost ready to burst into tears as he asks you: ""Where can I go to get my zipper repaired?"""
	.GSTR STR?112,"A wizard appears, carrying a zipper. He looks at you and asks: ""Where can I go to get organic vaseline?"""
	.GSTR STR?110,"A wizard appears, carrying a zipper. He looks very sick as he looks at you and asks porridgily: ""Where can I go to get my stomach pumped?"""
	.GSTR STR?109,"A wizard appears, carrying a zipper. He takes a pair of jeans out of the zipper, looks at you and asks eagerly: ""Where can I go to get my jeans embroidered?"""
	.GSTR STR?111,"A wizard appears, carrying a zipper. He takes a poodle out of the zipper and asks you: ""Where can I go to get my poodle clipped in this dungeon?"""
	.GSTR STR?108,"A wizard appeats, carrying a zipper. He takes a speaker out of the zipper, looks at you and asks eagerly: ""Where can I go to get my speakers fixed?"""
	.GSTR STR?104,"Aah! That was a nice drink."
	.GSTR STR?49,"Among the assorted rot and decay you find a thing that doesn't differ very much from the rest of the floor: a ZX Spectrum."
	.GSTR STR?344,"An elevator is a device that transport you vertically."
	.GSTR STR?65,"and LeBon's profundities. Very little wreckage floats ashore, in fact only one item."
	.GSTR STR?319,"Anything else you can do here?"
	.GSTR STR?289,"Are the bunnies important?"
	.GSTR STR?288,"Around the Old Farm"
	.GSTR STR?231,"As this is Werner's Quest III, not Trinity, you aren't at any atom bomb test site, but inside the toadstool. The floor here is covered with old leaves, inedible roots, edible roots (rotten), decay, rot, mould and general yeachhhiness."
	.GSTR STR?9,"As you approach the pedestal to take the Philatelist's Stone, you are immediately and inexplicably incinerated, and there is now one more severely-burnt skeleton in the room."
	.GSTR STR?35,"As you insert the spoon in the rock, the stone doors swing open with an ""Eep"", a ""Boing"" and a ""Falukropp"" respectively."
	.GSTR STR?88,"As you leave the pedestal, you are immediately incinerated and join the severely-burnt skeletons."
	.GSTR STR?96,"As you pull the lever, the room is filled with dwarves, hobbits, wizards, elves, martians, venusians, farmers, trolls, ogres and Rance the Dungeonkeeper. Rance says: ""Vell done! You've completed Werner's Kvest III. But zere's still a slight problem; what shall we do wiz you now? Ve have no problems left for you to tackle."" An extremely fat wizard steps forward. He introduces himself as Bulbouse, headmaster of the Necromancers' High School. He says: ""OK, OK, I'll take him, though I doubt he'll ever make a good necromancer...""
And so you've come to study at the Necromancers' High School..."
	.GSTR STR?52,"As you raise the spoon to strike, the now-familiar troll enters, brandishing an axe which he swings at you. Just before it reaches its goal, Rance the Dungeonkeeper materializes from thin air, grabbing to troll's wrist, thereby stopping him from completing his deed. Rance says: ""No! In zis parzicular zituation it iz aczilly allowed to perform zat aczion. It iz vithin ze conceptual framevork of this computerized event. Look here!"" He produces the long listing from his steaming briefcase and shows it to the troll. After studying the listing the troll leaves, murmuring not-so-kind things about Rance depriving him of his livelihood. Rance remarks to you: ""Now, conzinue vat you vere doing!"" You hit the bag-wearing person with the spoon, seemingly battering him into unconsciousness. Rance the Dungeonkeeper disappears in a puff of stage-craft."
	.GSTR STR?89,"As you touch the stamp with the stone, its colour changes to yellow."
	.GSTR STR?320,"Bar Area"
	.GSTR STR?409,"Baseball."
	.GSTR STR?313,"Bedroom Area"
	.GSTR STR?58,"Before you can even start to descend the well, Rance the Dungeonkeeper dashes out of the farmhouse, shouting: ""No! Not ze vell again!"" He ushers you into the tool shed."
	.GSTR STR?367,"Besides baking."
	.GSTR STR?405,"Bruce Springsteen is a rock artist."
	.GSTR STR?317,"Buy alcohol?"
	.GSTR STR?318,"BUY DRINK"
	.GSTR STR?259,"By pressing the buttons you can move the plastic gnome to eight different locations."
	.GSTR STR?271,"Can it be some sort of magic?"
	.GSTR STR?316,"Chat?"
	.GSTR STR?174,"climb"
	.GSTR STR?333,"Climb back up?"
	.GSTR STR?159,"close"
	.GSTR STR?42,"Closed."
	.GSTR STR?44,"Closed.

The room is now quiet, and the old man falls asleep."
	.GSTR STR?43,"Closed.

The sound of Bruce Springsteen can still be heard, although somewhat muffled. The old man says: ""Smart, young man! But I can still hear that horrible heavy metal music!"""
	.GSTR STR?410,"Cold showers."
	.GSTR STR?123,"Concealed upon your person are:"
	.GSTR STR?307,"COVER BRUCE WITH BLANKET"
	.GSTR STR?146,"Disc or Tape?"
	.GSTR STR?306,"Do you have something to cover Bruce with?"
	.GSTR STR?372,"Don't overcomplicate things."
	.GSTR STR?3,"Dropped."
	.GSTR STR?406,"Duran Duran was a pop band."
	.GSTR STR?375,"End Game"
	.GSTR STR?340,"Feel your way around."
	.GSTR STR?356,"Foggy Room Area"
	.GSTR STR?398,"Frank Zappa and other references"
	.GSTR STR?59,"From outside the tool shed you can hear the voice of Rance the Dungeonkeeper: ""Nasty person! Now stay in zere until you've learnt not to cauze me a lot of zrouble!"""
	.GSTR STR?352,"Further your education by reading it?"
	.GSTR STR?353,"GET BOOK. READ BOOK. GET STAMP."
	.GSTR STR?150,"get inside"
	.GSTR STR?369,"GIVE DRINK TO PREBEN"
	.GSTR STR?170,"give things to"
	.GSTR STR?267,"Have you examined everything?"
	.GSTR STR?243,"Have you examined the rock?"
	.GSTR STR?324,"Have you noticed the ceiling."
	.GSTR STR?256,"Have you noticed the floating buttons?"
	.GSTR STR?347,"Have you noticed the floor?"
	.GSTR STR?311,"Have you seen Poltergeist?"
	.GSTR STR?373,"Have you seen the lever?"
	.GSTR STR?277,"Have you tried climbing?"
	.GSTR STR?302,"Have you tried closing the door?"
	.GSTR STR?297,"Have you tried greeting him?"
	.GSTR STR?252,"Have you tried moving it around?"
	.GSTR STR?257,"Have you tried pushing them?"
	.GSTR STR?322,"Have you tried taking it wear the fully proteced body armour?"
	.GSTR STR?240,"Have you tried turning the escalator off?"
	.GSTR STR?296,"He certinaly won't let you board the boat."
	.GSTR STR?116,"He whispers: ""Do what ya shudd instead of disturbing woikin' people!"""
	.GSTR STR?298,"HELLO TAYLOR. (Hello Sailor, get it?)"
	.GSTR STR?332,"Help! I'm on the pedestal and can't leave."
	.GSTR STR?399,"Here's a complete list Frank Zappa and other references in the game."
	.GSTR STR?16,"He's old and wise-looking, but still there's something oddly inane about him, just as in your vision."
	.GSTR STR?17,"He's old and wise-looking, but still there's something oddly inane about him. He's also fast asleep."
	.GSTR STR?18,"He's wearing a pair of Levi's 501 (of course) and a white T-shirt, and he's singing ""Cover Me""."
	.GSTR STR?294,"HIT PERSON WITH SPOON"
	.GSTR STR?293,"Hmm. He won't let you. Maybe violence is the answer?"
	.GSTR STR?376,"How all the points are scored"
	.GSTR STR?280,"How do I enter the old farm"
	.GSTR STR?361,"How do I escape the ravine area?"
	.GSTR STR?276,"How do I get out of the well?"
	.GSTR STR?291,"How do I get the paper bag?"
	.GSTR STR?239,"How do I get up the escalator?"
	.GSTR STR?300,"How do I help the old man so he can get some sleep."
	.GSTR STR?260,"How do I open the door in the toadstool?"
	.GSTR STR?242,"How do I open the stone doors?"
	.GSTR STR?371,"How do I solve the end game?"
	.GSTR STR?326,"How do I solve the royal puzzle?"
	.GSTR STR?321,"How do I take the philatelist's stone?"
	.GSTR STR?348,"I you only had the right tool..."
	.GSTR STR?368,"If you don't have a drink then your out of luck and stuck."
	.GSTR STR?19,"If you hadn't known who it was, you could never have guessed that it's Bruce Springsteen, because he's covered with a blanket, which muffles his song."
	.GSTR STR?283,"If you looked like Thing-Fish, maybe?"
	.GSTR STR?335,"If you not been to the ravine area you are stuck."
	.GSTR STR?23,"In the book you find a green 3 skilling banco stamp."
	.GSTR STR?13,"In the rock there is a slot."
	.GSTR STR?359,"In WQII there was a usefull thing in the cave. Go see if it's still there."
	.GSTR STR?246,"INSERT SPOON IN SLOT."
	.GSTR STR?181,"INVISICLUES (tm)"
	.GSTR STR?237,"Is the printout important?"
	.GSTR STR?354,"Is the volcano important?"
	.GSTR STR?308,"Is there anything to do in the living room?"
	.GSTR STR?266,"Is there something of value here?"
	.GSTR STR?169,"it"
	.GSTR STR?28,"It appears to be a very expensive yacht. On the deck is standing John Taylor, who's occupied with ribs, rigging and all the other whatchammacallits of an average yacht."
	.GSTR STR?21,"It look just like an ordinary stone."
	.GSTR STR?254,"It moves by pressing one of the numbered buttons up on the vertex structure."
	.GSTR STR?262,"It opens by some sort of magic."
	.GSTR STR?278,"It seems like you are stuck."
	.GSTR STR?253,"It won't budge you have to find some other way to move it."
	.GSTR STR?24,"It's a form of sausage which smells horrible."
	.GSTR STR?15,"It's in as good shape as one could expect from a Spectrum that has been buried among rot and garbage for a while, or, by the way, from any Spectrum: slippery, mouldy and with a keyboard that reminds you of a bunch of well-worn erasers."
	.GSTR STR?341,"It's just a room. Nothing to see here."
	.GSTR STR?261,"It's no ordinary door."
	.GSTR STR?29,"It's small, black, thumb-shaped and equipped with a large red button labelled ""Large Red Button""."
	.GSTR STR?281,"It's the control center for the game. Rance will not let YOU in."
	.GSTR STR?175,"Jumping in place"
	.GSTR STR?364,"Just wait around. Eventually Rance will discover you and take you back."
	.GSTR STR?279,"Just wait. Eventually Rance will come and rescue you (don't forget the coin)."
	.GSTR STR?305,"Listen to the Boss."
	.GSTR STR?343,"Listen to the music?"
	.GSTR STR?250,"Locate the plastic gnome."
	.GSTR STR?160,"lock"
	.GSTR STR?151,"look inside"
	.GSTR STR?249,"Maybe something use the rails for transportation?"
	.GSTR STR?329,"Maybe the game mode is to hard for you?"
	.GSTR STR?245,"Maybe the spoon is multi-purpose?"
	.GSTR STR?282,"Maybe you can trick him?"
	.GSTR STR?315,"Mingle?"
	.GSTR STR?408,"Miscellaneous"
	.GSTR STR?130,"More..."
	.GSTR STR?338,"Museum"
	.GSTR STR?145,"N"
	.GSTR STR?360,"N. E. GET DEVICE."
	.GSTR STR?290,"No."
	.GSTR STR?355,"No. It's just scenary."
	.GSTR STR?69,"Nothing happens."
	.GSTR STR?129,"OK."
	.GSTR STR?128,"OK. That will probably be the best."
	.GSTR STR?158,"open"
	.GSTR STR?46,"Opened."
	.GSTR STR?40,"Opened.

The sound of Bruce Springsteen (albeit somewhat muffled) drifts through the door. The old man wakes up and screams: ""HELP! ASSAULT! EXPLOSION! FIRE! What? Oh no! Heavy metal music again!"""
	.GSTR STR?39,"Opened.

The sound of Bruce Springsteen singing ""Cover Me"" drifts through the door. The old man says: ""No! Not more heavy metal music!"""
	.GSTR STR?184,"P = Previous"
	.GSTR STR?154,"pick up"
	.GSTR STR?287,"Pick up the saw and the ladder."
	.GSTR STR?299,"Plain Cute"
	.GSTR STR?286,"Ponder your sins?"
	.GSTR STR?74,"Preben & Preben say nothing, but they stop you from taking the bottles."
	.GSTR STR?366,"Preben & Preben seems to have a hobby."
	.GSTR STR?75,"Preben & Preben take the drink and hand you a Danish pastry. They then remove their disguises and you see that it is the Thing-Fish and Rance the Dungeonkeeper respectively. The Thing-Fish says: ""Owaah! Thought ya was back in Werner's Quest I dere, din'tja? Whoe no! What time iddit?"" He reaches into Rance's briefcase and produces a grandfather clock, at which he gazes warily. ""Oh deahh! Ah'm late! I must go now an' arrange fo' de revengement I've been planning fo' ya!"" He disappears in a puff of stage-craft. Rance says: ""Vat? Vat about my clock? Vell, never mind! Let's get back to ze dungeon again!"" He pushes one of the walls gently, but nothing happens. He says: ""How strange! It vorked zis morning. Vell, anyvay, ve can poke a little."" He reaches into his briefcase, and the room begins to change..."
	.GSTR STR?404,"Preben & Preben was a standing sketch part in swedish televisions big saturday night entertainment block during the 80s."
	.GSTR STR?71,"Preben says: ""JA, HIER HABEN WIR ABER EINEN KLEINEN EINEN! DEN SOLLEN WIR TRINKEN STASSEN GEMASSEN SEIN!"" Preben leans over to Preben and whispers: ""Zat vas not Danish, you potato-headed jigaboo! It vas German!"" Preben whispers back: ""Wut? Goiman? Weren't dat no Danish? How embarrassim! We'd bettuh shurrup den, hadn't we?""
""Zat iz correct"", Preben replies, ""let's just hope zat he doesn't suspect anyzing."""
	.GSTR STR?264,"PRESS 5 (of the floating buttons)."
	.GSTR STR?331,"PRESS DEMO BUTTON"
	.GSTR STR?337,"PRESS RED BUTTON"
	.GSTR STR?66,"Pressed. You think that you see movement below, buy you're not sure about it."
	.GSTR STR?345,"Pressing the different buttons take you to different floors."
	.GSTR STR?374,"PULL LEVER"
	.GSTR STR?166,"Pulling"
	.GSTR STR?165,"Pushing"
	.GSTR STR?156,"put things in"
	.GSTR STR?155,"put things on"
	.GSTR STR?180,"Q = Main menu"
	.GSTR STR?186,"Q = Resume story"
	.GSTR STR?182,"Q = See hint menu"
	.GSTR STR?126,"Quit? That could be a severe mistake. Are you sure?"
	.GSTR STR?57,"Rance gazes down into the well and says: ""You're still zere, are you not? Too bad. I'll do some more poking."" He reaches into the briefcase again. Suddenly, strange things happen. The well begins to transform; slowly, the stones of its wall seem to melt away, and are replaced by the surroundings of another place..."
	.GSTR STR?60,"Rance looks up and notices you. He says: ""Get out! You are not allowed to be here! Ze very Dungeonkeeper's headquarters are situated in zis farmhouse. Zcram!"" He leads you out of the farmhouse."
	.GSTR STR?107,"Rance the dungeonkeeper appears. He takes the wizard by the arm and leads him off, saying: ""Questions, questions, questions, flooding into ze mind of ze conzerned young person zoday..."""
	.GSTR STR?54,"Rance the Dungeonkeeper comes gliding down the hand-rail. He reaches into his steaming briefcase and produces a long computer printout. He examines the printout and says to you: ""Vell, according to zis here assembly language listing, you vill, to komplete zis kvest, have to collect some items: A Danish pastry, a brovn paper bag viz peepholes in it, a Swedish yellow 3 skilling banco stamp, a Duran Duran album, a salami sausage and a basketball."" He tears off a piece of the printout and hands it to you. He then disappears in a puff of stage-craft."
	.GSTR STR?61,"Rance the Dungeonkeeper looks up and says: ""Hello zere, Thing-Fish!"""
	.GSTR STR?77,"Rance the Dungeonkeeper materializes from thin air. He says: ""Oh! Zere you are! Do you zink zis is some form of nostalgy zrip? Now, let's get back to zedungeon again."" He gently pushes one of the walls and..."
	.GSTR STR?56,"Rance the Dungeonkeeper re-appears at the top of the well with the clothes line, which he throws into the well. ""Oh zear"", he says, ""how ztupid of me. I should of course have kept one of the ends up here. I zink I vill have to poke into ze very programme to get you out of zere."" He reaches into the briefcase from which can be heard faint clicking, the only result being the disappearance of the clothes line."
	.GSTR STR?401,"Rance the Dungeonkeeper: Rance Mohammitz (Theodore Bikel) from the 1971 Zappa movie '200 Motels'."
	.GSTR STR?62,"Rance turns to you and says: ""By ze way, here I have a basketball."" He produces one from the steaming briefcase. ""Take it and conzeal it in a safe plaze."" He gives the basketball to you. Having done this, he takes a closer look at you, and notices that you're not the Thing-Fish. He removes the bag from your head with a triumphating smile. ""Ha! Thought you could fool me, did you not?"" You are thrown out and the paperbag with you."
	.GSTR STR?370,"Ravine / Danish Bakery"
	.GSTR STR?162,"read"
	.GSTR STR?178,"Recklessly incinerating"
	.GSTR STR?358,"Remember this area from Werner's Quest II?"
	.GSTR STR?247,"Round Room"
	.GSTR STR?177,"Rubbing"
	.GSTR STR?133,"s"
	.GSTR STR?349,"SAW FLOOR WITH SAW"
	.GSTR STR?378,"SCORE  ACTION"
	.GSTR STR?268,"SEARCH FLOOR."
	.GSTR STR?325,"See hint about the small room for more information."
	.GSTR STR?148,"Start the tape."
	.GSTR STR?53,"Suddenly, the oversized, chrome spoon appears in your hand, wildly glowing."
	.GSTR STR?163,"switch on and off"
	.GSTR STR?351,"Take the book?"
	.GSTR STR?2,"Taken."
	.GSTR STR?164,"Taking your frustration out on"
	.GSTR STR?167,"that"
	.GSTR STR?142,"That item isn't carried by you."
	.GSTR STR?105,"That was a very nice Danish pastry."
	.GSTR STR?122,"That's impossible."
	.GSTR STR?303,"That's not enough. You also have to do something else."
	.GSTR STR?27,"The album is called ""Duran Duran"" and is with the group of the same name."
	.GSTR STR?72,"The bargnome takes the coin and says: ""The same as usual, aye?"" You take a closer look at him and see that it's the same gnome as in Werner's Quest I. He hands you a drink."
	.GSTR STR?394,"The basketball - Rance has it inside the old farm. He will only give it to you if he thinks you're Thing-Fish."
	.GSTR STR?76,"The chute is too steep to ascend."
	.GSTR STR?7,"The clothes line is securely tied."
	.GSTR STR?395,"The danish pastry - In the danish bakery. Preben & Preben will give it to you in exchange for a drink."
	.GSTR STR?26,"The Danish pastry is a Danish cookie with chocolate in the middle."
	.GSTR STR?83,"The device emits an eep. Maybe it's broken."
	.GSTR STR?85,"The door closes and the elevator starts to vibrate. After a while, the vibrations stop and the door opens."
	.GSTR STR?45,"The door is already closed."
	.GSTR STR?41,"The door is already open."
	.GSTR STR?37,"The door is closed."
	.GSTR STR?38,"The door is open."
	.GSTR STR?393,"The Duran Duran album - On the yacht. You need to create chaos on the boat to get it."
	.GSTR STR?34,"The escalator goes downwards, and so you aren't really going anywhere. You return to Werner's Quest III."
	.GSTR STR?275,"The Great Hall"
	.GSTR STR?33,"The imposing stone door is closed."
	.GSTR STR?140,"The item to which you're referring isn't present."
	.GSTR STR?93,"The man isn't asleep, so it would be hard to wake him up."
	.GSTR STR?50,"The now-familiar troll enters. With his large axe, he chops you into a multitude of pieces, which evaporate."
	.GSTR STR?48,"The old man says: ""Oh, I can't get any sleep because of that rind in there and his heavy metal music!"". He points at the door."
	.GSTR STR?92,"The old man wakes up, obviously startled. He stares at you, then he takes out a steaming briefcase from under his sheets. He produces a long printout from it and gazes at it briefly. Then he says: ""Oh! You! That's right! Down here!"" He opens a concealed trap door in the floor and you gently descend the stairway below it. As you dot his, the old man runs past you down the stairs, changing clothes while running. He transforms from an old man via Rance the Dungeonkeeper to a small man with a three-piece suit, a bowtie and glasses. Finally, you reach the bottom of the staircase..."
	.GSTR STR?84,"The opening is too high to reach."
	.GSTR STR?402,"The Over-sized Chrome Spoon: Is from the song 'Muffin Man' on the 1975 Zappa & Captain Beefheart album 'Bongo Fury'."
	.GSTR STR?392,"The paper bag - Thing-Fish have it but you need to beat him unconscious before getting it."
	.GSTR STR?14,"The plastic gnome is about 4 ft high and holds its right index finger stretched out. On its head is positioned an antenna, and it's wheel-equipped feet are mounted on the railway."
	.GSTR STR?396,"The salami sausage - In the Royal Puzzle."
	.GSTR STR?106,"The salami tastes horrible, but you manage to consume it all."
	.GSTR STR?79,"The sandstone block is blocking your way down."
	.GSTR STR?67,"The screen changes: It now shows some kind of nature program."
	.GSTR STR?68,"The screen changes: It now shows the interior of a Danish bakery."
	.GSTR STR?301,"The sound is obivously disturbing him."
	.GSTR STR?51,"The spoon appears to be stuck in your hand. How strange."
	.GSTR STR?90,"The stamp is a yellow 3 skilling banco stamp already."
	.GSTR STR?30,"The toad is green and repellent."
	.GSTR STR?102,"The toad looks at you flirtily."
	.GSTR STR?31,"The TV set has two buttons marked ""1"" and ""2"" respectively. It is currently showing two intemperate Danish pastry cooks who seem to have vast difficulties to get started baking Danish pastries."
	.GSTR STR?32,"The TV set has two buttons marked ""1"" and ""2"" respectively. It is currently showing what appears to be some kind of nature programme, as the screen shows a canyon bottom."
	.GSTR STR?20,"The wheel-mounted gnome's index finger is pointing at the open white door."
	.GSTR STR?403,"The wizard that at times appears to ask existential questions is from the song 'Call Any Vegetable' from the 1972 Mothers of Invention album 'Just Another Band from L.A.'."
	.GSTR STR?397,"The yellow 3 skilling banco stamp - You find a green one in the cerise book. You have to change the color of it with the philatelist's stone."
	.GSTR STR?391,"The ZX Spectrum - Hidden in the rubble on the floor inside the toadstool."
	.GSTR STR?168,"them"
	.GSTR STR?81,"There is a grinding sound, and the walls begin to move. When they stop, they've formed a corridor leading south."
	.GSTR STR?400,"Thing-Fish: The unforgetable Thing-Fish (Ike Willis) from the 1984 Zappa album with the same name."
	.GSTR STR?201,"This is a remarkable spot in the dungeon. Remarkable, that is, because of its total lack of room description. More well-described locations can be found to the east, west or south."
	.GSTR STR?377,"This section should only be used as a last resort, or for your own interest after you've completed the game."
	.GSTR STR?78,"Time passes..."
	.GSTR STR?312,"TOUCH SCREEN"
	.GSTR STR?273,"Try kissing it."
	.GSTR STR?263,"Try moving the plastic gnome here."
	.GSTR STR?292,"Try taking the bag from the person."
	.GSTR STR?330,"Try the puzzle in demo mode instead."
	.GSTR STR?147,"Type in filename."
	.GSTR STR?161,"unlock"
	.GSTR STR?244,"Use the key."
	.GSTR STR?363,"Using the device is pointless. The goal is to escape this area with the device intact."
	.GSTR STR?176,"wake"
	.GSTR STR?407,"Various references to different Infocom games. Mostly Zork I-III, Enchanter and The Hitchhikers Guide to the Galaxy."
	.GSTR STR?173,"Waving your hands"
	.GSTR STR?157,"wear"
	.GSTR STR?284,"Wear paper bag before entering. "
	.GSTR STR?251,"What about the plastic gnome?"
	.GSTR STR?248,"What about the rails?"
	.GSTR STR?304,"What do I do about Bruce Springsteen"
	.GSTR STR?365,"What do I do in the bakery?"
	.GSTR STR?342,"What do I do in the elevator?"
	.GSTR STR?357,"What do I do in the ravine area?"
	.GSTR STR?346,"What do I do in the small room?"
	.GSTR STR?285,"What do I do in the toolshed?"
	.GSTR STR?269,"What do I do with the toad?"
	.GSTR STR?272,"What do you usually do with toads in fairy tales?"
	.GSTR STR?120,"What kind of talk is that? I'm not Encyclopedia Britannia y'know."
	.GSTR STR?119,"What next? "
	.GSTR STR?314,"What to do in the bar?"
	.GSTR STR?339,"What's the meaning of the foggy room?"
	.GSTR STR?265,"What's the point inside the toadstool?"
	.GSTR STR?350,"What's to do in the volcano chamber?"
	.GSTR STR?390,"Where are all the 'treasures' located"
	.GSTR STR?255,"Why am I standing on one leg atop the vertex structure?"
	.GSTR STR?295,"Will John Taylor give me an Duran Duran album?"
	.GSTR STR?144,"Y"
	.GSTR STR?238,"Yes."
	.GSTR STR?139,"You already have it."
	.GSTR STR?202,"You are almost choked by the cuteness as you walk in this seemingly endless meadow. However, a somewhat less cute place appears to lie to the south."
	.GSTR STR?199,"You are at another part of Plain Cute, but the cuteness remains: flowers, butterflies and rabbits."
	.GSTR STR?200,"You are at Plain Cute. It's a large meadow full of flowers, butterflies and cute little bunny rabbits. The cuteness continues to the south and west."
	.GSTR STR?235,"You are at the bottom of the 30 ft. deep well, standing in 5 inches of lukewarm water."
	.GSTR STR?228,"You are at the northern end of the ravine. To the east lies a small cave."
	.GSTR STR?216,"You are at the Royal Puzzle entrance, standing by a hole in the floor, which in all probability leads down to the Royal Puzzle. To the north there is a door through which you can see the museum. In the ceiling, too high to reach, is an opening."
	.GSTR STR?230,"You are at the southern end of a ravine. To the west there is a hole in the rock wall."
	.GSTR STR?226,"You are at the southern end of the north-south corridor formed by the Royal Puzzle. A ladder leads up."
	.GSTR STR?195,"You are at the southern part of the great hall. To the north lies the large triangular structure. The railway situation: east-west."
	.GSTR STR?210,"You are in a bedroom carved out of the rock. There's a bed and a bedside table here. Passages lead north, south and west, and a door leads east."
	.GSTR STR?221,"You are in a chamber carved out of the wall of a volcano. To the north is an opening through which you can see the aforementioned volcano, and to the south lies the elevator."
	.GSTR STR?213,"You are in a north-south passage. To the east is a pompous doorway over which hangs a sign reading: ""The Werner Dungeon Museum of Philately""."
	.GSTR STR?187,"You are in a round room with imposing stone doors leading east, west and south. A passage leads north."
	.GSTR STR?94,"You are in a small office at the bottom of the stairs. The small man is here. He eyes your possessions and produces the long listing from the ever-present steaming briefcase. After consulting this, he says: ""Well, it seems like you haven't got all the objects. Try again some other time."" The walls turn and..."
	.GSTR STR?95,"You are in a small office at the end of the staircase. The small man is here. He examines your possessions and says: ""Well, I think you've passed the test."" The walls turn and..."
	.GSTR STR?220,"You are in a small room whose floor consists of wooden planks. To the south lies an elevator."
	.GSTR STR?212,"You are in a the bar area of the dungeon. This big cave is full of bars, all of which are tended by gnomes. You can go north and south."
	.GSTR STR?208,"You are in a toolshed at a farm. The exit lies to the north."
	.GSTR STR?217,"You are in an elevator. On the wall are three buttons in the unlikely colours cerise, ochre and purple. The cerise button is glowing with a sickening glow."
	.GSTR STR?218,"You are in an elevator. On the wall are three buttons in the unlikely colours cerise, ochre and purple. The ochre button is glowing with a sickening glow."
	.GSTR STR?219,"You are in an elevator. On the wall are three buttons in the unlikely colours cerise, ochre and purple. The purple button is glowing with a sickening glow."
	.GSTR STR?232,"You are in cubical room. A lever protrudes from one wall, and above hangs a sign reading: ""The Final Conquest"""
	.GSTR STR?211,"You are in New Jersey. A door to the west leads to a bedroom in the Werner Dungeon (very peculiar indeed)."
	.GSTR STR?214,"You are in room filled with pea soup-like fog, which makes it impossible to see things further away than about 43 inches."
	.GSTR STR?227,"You are in the Danish Bakery. In the southern wall is set a large window, through which you can see a large number of trolls, ogres, dwarves, peasants and adventure game players gazing into the room. The southern wall also features a handle-less door. Preben & Preben, the two inebriate Danish pastry cooks, are here. You notice a vast quantity of bottles positioned near the two Danes."
	.GSTR STR?204,"You are in the farmhouse which contains Rance the Dungeonkeeper's headquarters. The house is cramped with monitors, headphones and other electronic equipment with which he has complete superintendence over every room in the dungeon. On the walls are hanging a multitude of disguises, which he uses when he's inspecting your eventual progresses. Rance is sitting at the table, probably figuring out new problems for you to tackle. The exit lies to the east."
	.GSTR STR?193,"You are in the great hall, east of the triangular structure. The railway is at this point stretching from the north to the south."
	.GSTR STR?190,"You are in the northeast corner of the great hall. To the southwest is a large triangular structure. There is a giant mushroom here, upon which is seated a toad. Therefore, you conclude, it's not so much a mushroom as a toadstool. In its stem is set a white door. The rails stretch from west to south."
	.GSTR STR?189,"You are in the northern end of a great hall. To the south stands a large triangular structure. What appears to be a railway stretches from east to west."
	.GSTR STR?188,"You are in the northwest corner of the great hall. To the southeast is a large triangular structure. Rails stretch from south to east."
	.GSTR STR?209,"You are in the old man's living room, which is furnished with a sofa, a table, a couple of armchairs and a TV set. The exit lies to the south."
	.GSTR STR?225,"You are in the Royal Puzzle, now arranged to form a north-south sandstone corridor, in whose northern end you stand."
	.GSTR STR?224,"You are in the Royal Puzzle, surrounded by sandstone walls."
	.GSTR STR?223,"You are in the Royal Puzzle: a small room with sandstone walls. On one of the walls are two buttons; a red one, marked ""Game"", and a green one, marked ""Demo"".
In the ceiling, too high to reach, is an opening."
	.GSTR STR?229,"You are in the small cave. From the sentence scribbled on one of the walls, ""Arthur Dent was here"", you conclude that Arthur Dent has been here, and that this might be the cave in which he lived during his visit to pre-historic earth. In one corner lies a pile of furs, among which no trace of freak worm-holes in the space-time fabric can be found."
	.GSTR STR?196,"You are in the southeast corner of the great hall. To the northwest you can see the large triangular structure. Oh, I forgot to mention: The rails at this particular point stretch from north to west."
	.GSTR STR?234,"You are in the southern end of a narrow north-south passage. At your feet is an opening throgh which a ladder emerges."
	.GSTR STR?194,"You are in the southwest corner of the great hall, in the middle of which stands a large triangular structure. The now-familiar railway turns north and east."
	.GSTR STR?215,"You are in the Werner Dungeon Museum of Philately, which has now been plundered and vandalised almost beyond recognition. The only intact item is a pedestal in the center of the room, around which lies a large number of severely-burnt skeletons. On the pedestal there is a plaque reading: ""The Philatelist's Stone, which turns ordinary stamps into yellow 3 skilling banco."". You notice that the ceiling is made of wooden planks. To the west lies a pompous doorway and a smaller door leads south."
	.GSTR STR?191,"You are in the west end of the great hall. The large triangular structure lies to the east. Some rails are lying here, by some reason arranged in the north-southern direction."
	.GSTR STR?10,"You are now wearing the bag over your head. You can see quite well through the peep-holes, but in spite of this you feel very silly."
	.GSTR STR?222,"You are on the pedestal in the Werner Dungeon Museum of Philately. All around you, on the floor, are severely-burnt skeletons and there's a hole in the wooden ceiling."
	.GSTR STR?197,"You are sitting on the toadstool beside the toad."
	.GSTR STR?233,"You are standing at a hole in the floor, through which you can see the entrance to the Royal Puzzle."
	.GSTR STR?236,"You are standing at the bottom of a short escalator, which is going downwards. A passage leads south."
	.GSTR STR?192,"You are standing at the foot of the triangular structure in the middle of the great hall. Stairs lead up the hypotenuse of the triangle."
	.GSTR STR?206,"You are standing at the shore of a presumably large ocean. As this is a shore, and not an island, the water does not prevent motion to the north or east."
	.GSTR STR?205,"You are standing in an old farm, which by some peculiar reason is situated in the dungeon. The farm house lies to the west and to the south lies a tool shed. In the middle of the yard is an approximately 30 ft. deep well."
	.GSTR STR?198,"You are standing on one leg on the pin-sharp vertex of the triangular structure. Inexplicably suspended in mid-air are eight buttons marked from 1 to 8."
	.GSTR STR?309,"You can always watch some TV."
	.GSTR STR?310,"You can even change the channel by pressing the buttons."
	.GSTR STR?118,"You can see:"
	.GSTR STR?362,"You can use the device."
	.GSTR STR?121,"You can't move in that direction."
	.GSTR STR?100,"You can't reach the toad."
	.GSTR STR?323,"You can't take the stone from here. The burglary system is to good."
	.GSTR STR?241,"You can't. The Escalator is only going down."
	.GSTR STR?99,"You connect the ZX Spectrum to the TV set and start it up. The sight of the startup message, however, makes you sick, and so you turn it off again."
	.GSTR STR?47,"You cover Bruce Springsteen with the blanket, and the sound of his song is muffled."
	.GSTR STR?274,"You don't need the toad for anything in this story."
	.GSTR STR?115,"You enter the ocean and splash around for a while, but nothing exciting happens, and so you get out of the water."
	.GSTR STR?114,"You enter the ocean. John Taylor steers the yacht nearer and picks you up. He looks you up and down for a while before he discards you and throws you into the ocean again. You scramble out of the water."
	.GSTR STR?203,"You gaze across the meadow to find something ugly, or at least mediocre, but it is hopeless; the cuteness stretches in all directions."
	.GSTR STR?207,"You grit your teeth at the sight of more butterflies, flowers and bunny rabbits; you're still on Plain Cute."
	.GSTR STR?103,"You hang the blanket on the clothes line."
	.GSTR STR?73,"You have no money."
	.GSTR STR?135,"You have scored"
	.GSTR STR?131,"You have taken "
	.GSTR STR?258,"You have to examine the great hall to see if something changed."
	.GSTR STR?328,"You have to push the walls in the right order."
	.GSTR STR?327,"You have to push the walls."
	.GSTR STR?86,"You have walked into a steel door."
	.GSTR STR?80,"You hear a grinding sound; the walls are moving, and you are being shuffled around by them. Finally, they stop."
	.GSTR STR?55,"You hear a voice overhead: ""Hey you zown zere!"" You look up and notice Rance the Dungeonkeeper gazing into the well. He's wearing braces and a silly straw hat, and he's carrying the steaming briefcase. He says: ""It is I, Rance ze Dungeonkeeper! I'm not very good at zis dungeonkeeping bizniz, but according to zis here assembly language listing"" he says, producing the listing from the briefcase, ""I vill appear now, zressed up like a simple farm hand, and zrow youze clothes line. Vait a moment."" He leaves."
	.GSTR STR?101,"You kiss the toad. Nothing happens. The toad croaks: ""Thanks, sailor! But it's too strong a curse to be lifted by a kiss. Come back when you're a necromancer or something. I'll probably be in the Ivetofta Swamp by then."""
	.GSTR STR?12,"You lean the ladder against the toadstool, enabling you to climb it."
	.GSTR STR?270,"You need a ladder to reach it."
	.GSTR STR?334,"You need some sort of transportation out of here."
	.GSTR STR?336,"You need the black device."
	.GSTR STR?4,"You pull the spoon out of the rock."
	.GSTR STR?98,"You push one of the walls, but nothing happens."
	.GSTR STR?97,"You push the wall, which slides forward. You follow it. Behind you other walls change position."
	.GSTR STR?36,"You put the spoon back into the rock."
	.GSTR STR?5,"You reach for the bag, but the person dodges your grip."
	.GSTR STR?6,"You remove the bag from the head of the seemingly unconscious person. Your suspicion is comfirmed: It's the Thing-Fish. ""Peek-a-boo, boy, peek-a-boo!"", he says, ""Ya sho'nuff didn't expect me to be in a cute place like dis, didja? I'll tell ya one thing: Dat deahhh froot joos bidniz wuz jes' a gimmick. De trooth is dat I has dicovuhd sum really really comprommuhtatim stuff 'bouts y'all, an' as soon as de appropriot measures has been taken, I'll sho'nuff be back, wit avengance!"" He takes a pause to gesticulate. ""Hah! I sho'nuff doesn't forgets easily, does I? See ya latuh, boy!"" He disappears in a puff of stage-craft."
	.GSTR STR?63,"You remove the bag. Rance, seeing this, shouts: ""Vat? You here? Get out at once, you nasty person!"" He ushers you out of the farmhouse."
	.GSTR STR?11,"You remove the bag. This makes you feel somewhat less silly."
	.GSTR STR?87,"You saw a round hole in the floor. Unfortunately, you stand in the middle of it. Therefore, you fall down through the hole and land on a pedestal in the room below. The planks disappear by the magic of stage-craft."
	.GSTR STR?64,"You say ""Hello Taylor"". John Taylor hears this and raises his hands to wave at you. Doing this, he lets go of the ribs, railing and whatchammacallits with which he was fiddling. As a result of this, the whole rigging falls down on the deck with a loud thump. This thump has obviously startled Simon LeBon, who has been resting (or something) below the deck. He dashes up onto the deck, thereby stumbling on the pieces of string that lie scattered on the deck and falls overboard. Well, almost. His right foot gets stuck in the bulwark rail and he describes a beautiful arch, his head hitting the hull right above the waterline. Seeing this, Taylor breaks into uncontrollable laughter. His paroxysms, along with the gesticulating of LeBon, set the boat rocking. In fact, it rocks so much that it capsizes and sinks, accompanied by Taylor's laughter"
	.GSTR STR?1,"You see nothing special."
	.GSTR STR?91,"You shouldn't finger at stamps, it might hurt the teeth."
	.GSTR STR?8,"You take the blanket off Bruce Springsteen. The sound of ""Cover Me"" can once again be heard clearly."
	.GSTR STR?70,"You touch the screen and find yourself transported to another place..."
	.GSTR STR?138,"Your hands are full."
	.GSTR STR?141,"Your load is too heavy."
	.GSTR STR?82,"Your surroundings shift..."
	.GSTR STR?143,"You're already wearing it."
	.GSTR STR?137,"You're not wearing it."
	.ENDI
